services:
  - type: worker
    name: quant-alpha-worker
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "TRUE"
    plan: free
    autoDeploy: true
    schedule: "*/5 * * * *"